Failed to complete cronjob at ('*/1 * * * *', 'Markowitz.cron.cron.oracle_wakeup')
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django_crontab/crontab.py", line 145, in run_job
    func(*job_args, **job_kwargs)
  File "/home/ubuntu/Crypto-Efficient-Asset-Management/Markowitz/cron/cron.py", line 27, in oracle_wakeup
    tx = oracle.functions.wakeupOracle().buildTransaction({'nonce': w3oracle.eth.getTransactionCount(WALLET_ADDRESS)})
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/contract.py", line 1079, in buildTransaction
    return build_transaction_for_function(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/contract.py", line 1648, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/_utils/transactions.py", line 121, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/_utils/transactions.py", line 67, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/ubuntu/.local/lib/python3.8/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32016, 'data': 'Reverted', 'message': 'The execution failed due to an exception.'}
